packages:
  - apps/*
  - packages/*
  - blocks/*
  - e2e/*

catalog:
  '@sentry/nextjs': ^10.26.0
  '@supabase/auth-js': 2.97.0
  '@supabase/postgrest-js': 2.97.0
  '@supabase/realtime-js': 2.97.0
  '@supabase/supabase-js': 2.97.0
  '@types/node': ^22.0.0
  '@types/react': ^18.3.0
  '@types/react-dom': ^18.3.0
  next: ^15.5.10
  lodash-es: ^4.17.23
  lodash: ^4.17.23
  react: ^18.3.0
  react-dom: ^18.3.0
  recharts: ^2.15.4
  tailwindcss: 3.4.1
  tsx: 4.20.3
  typescript: ~5.9.0
  valtio: ^1.12.0
  vite: ^7.1.11
  vitest: ^3.2.0
  zod: 3.25.76

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - contentlayer2
  - core-js
  - es5-ext
  - esbuild
  - libpg-query
  - msw
  - node-pty
  - protobufjs
  - sharp

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@ai-sdk/*'
  - '@supabase/*'
  - 'next'
  - '@next/*'
  - ai
  - js-yaml
  - supabase
  - iceberg-js
  - '@vitejs/plugin-rsc'
  - stripe-experiment-sync # TODO(matlin) remove, temp just to unblock launch
  - braintrust
  - tar
  - diff
  - lodash-es
  - lodash
  - next-mdx-remote

onlyBuiltDependencies:
  - supabase

overrides:
  '@redocly/respect-core>form-data': ^4.0.4
  '@redocly/respect-core>js-yaml': ^4.1.1
  esbuild: ^0.25.2
  nodemailer: ^7.0.11
  lodash-es: 'catalog:'
  lodash: 'catalog:'
  payload>undici: ^7.18.2
  refractor>prismjs: ^1.30.0
  tar: ^7.5.7
  tmp: ^0.2.4
